"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { CheckCircle2, Search } from "lucide-react";

import { useRFTStore } from "@/store/rft-store";
import { useSpoolErectionStages } from "@/store/erection-rollup";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { cn } from "@/lib/utils";

type RFTFilter = "All" | "RFT" | "Pending";

const RFT_FILTERS: RFTFilter[] = ["All", "RFT", "Pending"];

function StatusChip({
  status,
  count,
  active,
  onClick,
}: {
  status: RFTFilter;
  count: number;
  active: boolean;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors",
        active
          ? "border-sky-600 bg-sky-600 text-white"
          : "border-slate-200 bg-white text-slate-600 hover:border-slate-300",
      )}
    >
      {status}
      <span
        className={cn(
          "inline-flex h-[18px] min-w-[18px] items-center justify-center rounded-full text-[10px] font-semibold",
          active ? "bg-sky-500 text-white" : "bg-slate-100 text-slate-600",
        )}
      >
        {count}
      </span>
    </button>
  );
}

function RFTDetailPanel({
  spoolNo,
  open,
  onOpenChange,
}: {
  spoolNo: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const rftRecord = useRFTStore((s) => s.getRecord)(spoolNo ?? "");

  if (!spoolNo) return null;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-md overflow-y-auto">
        <SheetHeader className="mb-4">
          <SheetTitle className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
            {spoolNo}
          </SheetTitle>
          <SheetDescription>Ready For Test — auto-derived record</SheetDescription>
        </SheetHeader>

        {rftRecord ? (
          <div className="space-y-4 text-sm">
            <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3">
              <p className="font-medium text-emerald-800">RFT Confirmed</p>
              <p className="text-emerald-700 mt-1">Date: {rftRecord.rftDate}</p>
            </div>

            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                Predecessor audit trail
              </p>
              <div className="space-y-2 rounded-lg border p-3">
                <div className="flex justify-between">
                  <span className="text-slate-600">To Site</span>
                  <span className="font-medium">{rftRecord.predecessors.toSiteDate}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Erected</span>
                  <span className="font-medium">{rftRecord.predecessors.erectedDate}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Welded / Bolted</span>
                  <span className="font-medium">{rftRecord.predecessors.weldedBoltedDate}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Supported</span>
                  <span className="font-medium">{rftRecord.predecessors.supportedDate}</span>
                </div>
              </div>
            </div>

            <div className="rounded-lg border bg-slate-50 p-3 text-xs text-slate-500">
              Auto-generated by system — no manual confirmation required.
            </div>
          </div>
        ) : (
          <div className="rounded-lg border bg-amber-50 p-4 text-sm text-amber-800">
            Not yet RFT. All four predecessor steps must be confirmed first.
          </div>
        )}
      </SheetContent>
    </Sheet>
  );
}

export function RFTView() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const rftRecords = useRFTStore((s) => s.records);
  const spoolStages = useSpoolErectionStages();
  const [search, setSearch] = useState("");
  const [selectedSpool, setSelectedSpool] = useState<string | null>(null);
  const [panelOpen, setPanelOpen] = useState(false);

  const urlFilter = searchParams.get("filter") as RFTFilter | null;
  const [activeFilter, setActiveFilter] = useState<RFTFilter>(
    urlFilter && RFT_FILTERS.includes(urlFilter) ? urlFilter : "All",
  );

  const rftSet = useMemo(
    () => new Set(rftRecords.map((r) => r.spoolNo)),
    [rftRecords],
  );

  const allRows = useMemo(() => {
    return spoolStages.map(({ spoolNo, stage }) => ({
      spoolNo,
      stage,
      isRFT: rftSet.has(spoolNo),
      rftRecord: rftRecords.find((r) => r.spoolNo === spoolNo),
    }));
  }, [spoolStages, rftSet, rftRecords]);

  const counts = useMemo(
    () => ({
      All: allRows.length,
      RFT: allRows.filter((r) => r.isRFT).length,
      Pending: allRows.filter((r) => !r.isRFT).length,
    }),
    [allRows],
  );

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return allRows.filter((row) => {
      if (activeFilter === "RFT" && !row.isRFT) return false;
      if (activeFilter === "Pending" && row.isRFT) return false;
      if (q && !row.spoolNo.toLowerCase().includes(q)) return false;
      return true;
    });
  }, [allRows, activeFilter, search]);

  function handleFilterChange(f: RFTFilter) {
    setActiveFilter(f);
    const params = new URLSearchParams(searchParams.toString());
    if (f === "All") {
      params.delete("filter");
    } else {
      params.set("filter", f);
    }
    router.replace(`/erection/rft?${params.toString()}`, { scroll: false });
  }

  function handleRowClick(spoolNo: string) {
    setSelectedSpool(spoolNo);
    setPanelOpen(true);
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        {RFT_FILTERS.map((f) => (
          <StatusChip
            key={f}
            status={f}
            count={counts[f]}
            active={activeFilter === f}
            onClick={() => handleFilterChange(f)}
          />
        ))}
        <div className="relative ml-auto w-56">
          <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search spool..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-8 pl-8 text-xs"
          />
        </div>
      </div>

      <div className="rounded-lg border bg-white">
        <table className="w-full border-collapse text-left text-sm">
          <thead className="border-b bg-slate-50 text-xs uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-3 font-medium">Spool No</th>
              <th className="px-4 py-3 font-medium">Erection Stage</th>
              <th className="px-4 py-3 font-medium">RFT Date</th>
              <th className="px-4 py-3 font-medium">Status</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 && (
              <tr>
                <td colSpan={4} className="px-4 py-8 text-center text-muted-foreground">
                  No spools match the current filter.
                </td>
              </tr>
            )}
            {filtered.map((row) => (
              <tr
                key={row.spoolNo}
                onClick={() => handleRowClick(row.spoolNo)}
                className="cursor-pointer border-b last:border-0 hover:bg-slate-50"
              >
                <td className="px-4 py-3 font-medium text-slate-900">
                  {row.spoolNo}
                </td>
                <td className="px-4 py-3 text-slate-600">{row.stage}</td>
                <td className="px-4 py-3 text-slate-600">
                  {row.rftRecord?.rftDate ?? "—"}
                </td>
                <td className="px-4 py-3">
                  {row.isRFT ? (
                    <Badge className="border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-50">
                      <CheckCircle2 className="mr-1 h-3 w-3" />
                      RFT
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-700">
                      Pending
                    </Badge>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <RFTDetailPanel
        spoolNo={selectedSpool}
        open={panelOpen}
        onOpenChange={setPanelOpen}
      />
    </div>
  );
}
