import type { ErectionStatus, FieldWeldJoint } from "@/lib/erection-weld-data"
import { AREA_ZONES } from "@/lib/erection-weld-data"

export type SpoolErectionStage =
  | "Awaiting Release"
  | "To Site"
  | "Field Material Check"
  | "Erected"
  | "Welded/Bolted"
  | "Supported"
  | "RFT"

export const ERECTION_STAGE_ORDER: SpoolErectionStage[] = [
  "Awaiting Release",
  "To Site",
  "Field Material Check",
  "Erected",
  "Welded/Bolted",
  "Supported",
  "RFT",
]

export const ERECTION_STAGE_COLOR: Record<
  SpoolErectionStage,
  { bg: string; text: string; rail: string }
> = {
  "Awaiting Release": {
    bg: "bg-slate-50",
    text: "text-slate-600",
    rail: "bg-slate-300",
  },
  "To Site": {
    bg: "bg-amber-50",
    text: "text-amber-700",
    rail: "bg-amber-500",
  },
  "Field Material Check": {
    bg: "bg-cyan-50",
    text: "text-cyan-700",
    rail: "bg-cyan-500",
  },
  Erected: {
    bg: "bg-sky-50",
    text: "text-sky-700",
    rail: "bg-sky-500",
  },
  "Welded/Bolted": {
    bg: "bg-violet-50",
    text: "text-violet-700",
    rail: "bg-violet-500",
  },
  Supported: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    rail: "bg-emerald-500",
  },
  RFT: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    rail: "bg-emerald-700",
  },
}

export interface ToSiteRecord {
  spoolNo: string
  receivedDate: string
  receivedBy: string
  w24FormNo: string
  remark?: string
}

export const AREA_SUPERVISORS = [
  "SUP-01",
  "SUP-02",
  "SUP-03",
  "SUP-04",
] as const

export type AreaSupervisor = (typeof AREA_SUPERVISORS)[number]

export const PLACEMENT_LOCATIONS = AREA_ZONES
export type PlacementLocation = (typeof PLACEMENT_LOCATIONS)[number]

export interface ErectedRecord {
  spoolNo: string
  erectedDate: string
  erectedBy: AreaSupervisor
  w24FormNo: string
  placementLocation: PlacementLocation
  elevation?: string
  remark?: string
}

export interface WeldedBoltedRecord {
  spoolNo: string
  confirmedDate: string
  confirmedBy: string
  w24FormNo: string
  weldedJointCount: number
  boltedJointCount: number
  remark?: string
}

export type SupportType = "Hanger" | "Anchor" | "Guide" | "Spring"
export type SupportStatus = "Not Started" | "Erected" | "Welded"

export interface SupportItem {
  id: string
  spoolNo: string
  tag: string
  type: SupportType
  status: SupportStatus
}

export interface RFTRecord {
  spoolNo: string
  rftDate: string
  autoGenerated: true
  predecessors: {
    toSiteDate: string
    erectedDate: string
    weldedBoltedDate: string
    supportedDate: string
  }
}

export function isSpoolRFTEligible(
  spoolNo: string,
  toSiteRecord?: ToSiteRecord,
  erectedRecord?: ErectedRecord,
  weldedBoltedRecord?: WeldedBoltedRecord,
  supportedRecord?: SupportedRecord,
  flangeRollup?: SpoolFlangeBoltRollup,
): boolean {
  return (
    toSiteRecord?.spoolNo === spoolNo &&
    erectedRecord?.spoolNo === spoolNo &&
    weldedBoltedRecord?.spoolNo === spoolNo &&
    supportedRecord?.spoolNo === spoolNo &&
    (!flangeRollup || flangeRollup.totalBolts === 0 || flangeRollup.allVerified)
  )
}

export interface SupportedRecord {
  spoolNo: string
  confirmedDate: string
  confirmedBy: AreaSupervisor
  w23FormNo: string
  totalSupports: number
  remark?: string
}

// ---------------------------------------------------------------------------
// Field Material Check data model (I7)
// ---------------------------------------------------------------------------

export type FieldMaterialCheckStatus = "Pending" | "Cleared" | "Non-conformance"

export interface FieldHeatPiece {
  id: string
  fieldJointId: string
  tag: string
  type: "Pipe Stub" | "Fitting" | "Flange" | "Weld Stub"
  heatNumber: string
  millCertRef?: string
  status: FieldMaterialCheckStatus
  ncRemark?: string
}

export interface FieldMaterialCheckRecord {
  fieldJointId: string
  spoolNo: string
  pieces: FieldHeatPiece[]
  inspector?: string
  signedOffDate?: string
  wmcFormNo?: string
  remark?: string
  nonConformanceCount: number
}

export interface SpoolFieldMCRollup {
  totalJoints: number
  clearedJoints: number
  ncJoints: number
  pendingJoints: number
  allCleared: boolean
}

export function computeSpoolFieldMCRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "id">[],
  mcRecords: Pick<FieldMaterialCheckRecord, "fieldJointId" | "pieces" | "signedOffDate">[],
): SpoolFieldMCRollup {
  const joints = fieldWelds.filter((w) => w.spoolNo === spoolNo)
  const totalJoints = joints.length
  const jointIds = new Set(joints.map((j) => j.id))

  let clearedJoints = 0
  let ncJoints = 0
  let pendingJoints = 0

  for (const record of mcRecords) {
    if (!jointIds.has(record.fieldJointId)) continue
    const ncCount = record.pieces.filter((p) => p.status === "Non-conformance").length
    if (record.signedOffDate) {
      clearedJoints += 1
    } else if (ncCount > 0) {
      ncJoints += 1
    } else {
      pendingJoints += 1
    }
  }

  // Joints with no MC record at all count as pending
  const jointsWithRecord = new Set(
    mcRecords.filter((r) => jointIds.has(r.fieldJointId)).map((r) => r.fieldJointId),
  )
  pendingJoints += totalJoints - jointsWithRecord.size

  const allCleared = totalJoints > 0 && clearedJoints === totalJoints

  return { totalJoints, clearedJoints, ncJoints, pendingJoints, allCleared }
}

export interface SpoolWBRollup {
  weldJointsTotal: number
  weldJointsDone: number
  boltJointsTotal: number
  boltJointsDone: number
  allDone: boolean
}

export function computeSpoolWBRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "erectionStatus" | "fieldJointType">[],
): SpoolWBRollup {
  const joints = fieldWelds.filter((w) => w.spoolNo === spoolNo)

  const weldJoints = joints.filter(
    (w) => w.fieldJointType === "Butt Weld" || w.fieldJointType === "Socket Weld",
  )
  const boltJoints = joints.filter((w) => w.fieldJointType === "Flange Bolt")

  const weldDoneStatuses = new Set<ErectionStatus>(["Welded", "Supported", "RFT"])
  const boltDoneStatuses = new Set<ErectionStatus>(["Bolted", "Supported", "RFT"])

  const weldJointsTotal = weldJoints.length
  const weldJointsDone = weldJoints.filter((w) => weldDoneStatuses.has(w.erectionStatus)).length
  const boltJointsTotal = boltJoints.length
  const boltJointsDone = boltJoints.filter((w) => boltDoneStatuses.has(w.erectionStatus)).length

  const allDone =
    weldJointsTotal === weldJointsDone &&
    boltJointsTotal === boltJointsDone &&
    (weldJointsTotal > 0 || boltJointsTotal > 0)

  return {
    weldJointsTotal,
    weldJointsDone,
    boltJointsTotal,
    boltJointsDone,
    allDone,
  }
}

export interface SpoolSupportRollup {
  total: number
  erected: number
  welded: number
  allWelded: boolean
}

export function computeSpoolSupportRollup(
  spoolNo: string,
  supportItems: Pick<SupportItem, "spoolNo" | "status">[],
): SpoolSupportRollup {
  const items = supportItems.filter((item) => item.spoolNo === spoolNo)
  const total = items.length
  const erected = items.filter(
    (item) => item.status === "Erected" || item.status === "Welded",
  ).length
  const welded = items.filter((item) => item.status === "Welded").length
  const allWelded = total > 0 && welded === total

  return { total, erected, welded, allWelded }
}

export const TO_SITE_SEED: ToSiteRecord[] = [
  {
    spoolNo: "PL-TK100-003-A",
    receivedDate: "2025-05-16",
    receivedBy: "SUP-02",
    w24FormNo: "W24-2025-0142",
    remark: "Unloaded near compressor skid south access.",
  },
  {
    spoolNo: "PL-TK100-004-A",
    receivedDate: "2025-05-16",
    receivedBy: "SUP-03",
    w24FormNo: "W24-2025-0146",
    remark: "Supervisor confirmed supports available at Area A.",
  },
  {
    spoolNo: "PL-CW200-005-A",
    receivedDate: "2025-05-15",
    receivedBy: "SUP-01",
    w24FormNo: "W24-2025-0138",
    remark: "Delivered with insulation clearance hold note resolved on site.",
  },
  {
    spoolNo: "PL-CW200-005-B",
    receivedDate: "2025-05-17",
    receivedBy: "SUP-04",
    w24FormNo: "W24-2025-0155",
    remark: "Transport scheduled for early morning.",
  },
  {
    spoolNo: "PL-FU300-007-A",
    receivedDate: "2025-05-17",
    receivedBy: "SUP-01",
    w24FormNo: "W24-2025-0156",
    remark: "Crane slot booked for 09:00.",
  },
]

export const ERECTED_SEED: ErectedRecord[] = [
  {
    spoolNo: "PL-TK100-003-A",
    erectedDate: "2025-05-17",
    erectedBy: "SUP-02",
    w24FormNo: "W24-2025-0148",
    placementLocation: "Area B - Compressor Hall",
    elevation: "EL +8.2",
    remark: "Crane-lifted and aligned to north rack.",
  },
  {
    spoolNo: "PL-FU300-007-A",
    erectedDate: "2025-05-17",
    erectedBy: "SUP-03",
    w24FormNo: "W24-2025-0157",
    placementLocation: "Area D - Utility Corridor",
    elevation: "EL +4.0",
    remark: "Temporary tag line used due to wind.",
  },
  {
    spoolNo: "PL-CW200-005-A",
    erectedDate: "2025-05-16",
    erectedBy: "SUP-01",
    w24FormNo: "W24-2025-0139",
    placementLocation: "Area C - Tank Farm",
    elevation: "EL +12.5",
    remark: "Confirmed by area supervisor after visual check.",
  },
]

export const WELDED_BOLTED_SEED: WeldedBoltedRecord[] = [
  {
    spoolNo: "PL-TK100-003-A",
    confirmedDate: "2025-05-18",
    confirmedBy: "QC-ENG-01",
    w24FormNo: "W24-2025-0149",
    weldedJointCount: 0,
    boltedJointCount: 2,
    remark: "Flange bolt torqued and inspected per W-24.",
  },
  {
    spoolNo: "PL-CW200-005-A",
    confirmedDate: "2025-05-18",
    confirmedBy: "QC-ENG-02",
    w24FormNo: "W24-2025-0150",
    weldedJointCount: 1,
    boltedJointCount: 1,
    remark: "Field butt weld completed per W-24.",
  },
  {
    spoolNo: "PL-FU300-007-A",
    confirmedDate: "2025-05-18",
    confirmedBy: "QC-ENG-03",
    w24FormNo: "W24-2025-0151",
    weldedJointCount: 0,
    boltedJointCount: 2,
    remark: "Flange bolt torqued per W-24.",
  },
]

const ERECTION_STATUS_RANK: Record<ErectionStatus, number> = {
  "Not Started": 0,
  "To Site": 1,
  Erected: 2,
  Welded: 3,
  Bolted: 3,
  Supported: 4,
  RFT: 5,
}

export function deriveSpoolErectionStage(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "erectionStatus">[],
  toSiteRecord?: ToSiteRecord,
  erectedRecord?: ErectedRecord,
  weldedBoltedRecord?: WeldedBoltedRecord,
  supportedRecord?: SupportedRecord,
  rftRecord?: RFTRecord,
  fieldMCRollup?: SpoolFieldMCRollup,
): SpoolErectionStage {
  if (rftRecord?.spoolNo === spoolNo) return "RFT"
  const statuses = fieldWelds
    .filter((fieldWeld) => fieldWeld.spoolNo === spoolNo)
    .map((fieldWeld) => fieldWeld.erectionStatus)

  if (statuses.length === 0) {
    if (erectedRecord) return "Erected"
    // Field Material Check gate for spools with no field welds but MC records
    if (
      toSiteRecord &&
      fieldMCRollup &&
      fieldMCRollup.totalJoints > 0 &&
      (!fieldMCRollup.allCleared || !erectedRecord)
    ) {
      if (!fieldMCRollup.allCleared) return "Field Material Check"
      if (!erectedRecord) return "Field Material Check"
    }
    return toSiteRecord ? "To Site" : "Awaiting Release"
  }

  if (supportedRecord) {
    return "Supported"
  }

  if (statuses.every((status) => ERECTION_STATUS_RANK[status] >= 3)) {
    // Gating: Welded/Bolted stage requires explicit QC sign-off record
    if (weldedBoltedRecord) {
      return "Welded/Bolted"
    }
    // Without record, cap at Erected if erectedRecord exists, otherwise fall through
    if (erectedRecord) {
      return "Erected"
    }
  }

  if (statuses.every((status) => ERECTION_STATUS_RANK[status] >= 2)) {
    return "Erected"
  }

  if (
    erectedRecord &&
    statuses.every((status) => ERECTION_STATUS_RANK[status] <= 2)
  ) {
    return "Erected"
  }

  // Field Material Check gate (inserted between To Site and Erected)
  if (toSiteRecord && fieldMCRollup && fieldMCRollup.totalJoints > 0) {
    if (!fieldMCRollup.allCleared) {
      return "Field Material Check"
    }
    if (!erectedRecord) {
      return "Field Material Check"
    }
    // allCleared + erectedRecord → fall through to existing logic
  }

  if (toSiteRecord) {
    return "To Site"
  }

  if (statuses.some((status) => ERECTION_STATUS_RANK[status] >= 1)) {
    return "To Site"
  }

  return "Awaiting Release"
}


export const SUPPORT_SEED: SupportItem[] = [
  // PL-TK100-003-A — all welded (I5 Confirmed)
  {
    id: "SUP-PL-TK100-003-A-01",
    spoolNo: "PL-TK100-003-A",
    tag: "H-1042",
    type: "Hanger",
    status: "Welded",
  },
  {
    id: "SUP-PL-TK100-003-A-02",
    spoolNo: "PL-TK100-003-A",
    tag: "A-205",
    type: "Anchor",
    status: "Welded",
  },
  {
    id: "SUP-PL-TK100-003-A-03",
    spoolNo: "PL-TK100-003-A",
    tag: "G-301",
    type: "Guide",
    status: "Welded",
  },
  {
    id: "SUP-PL-TK100-003-A-04",
    spoolNo: "PL-TK100-003-A",
    tag: "S-101",
    type: "Spring",
    status: "Welded",
  },
  // PL-CW200-005-A — all welded, no SupportedRecord (I5 Ready to Confirm)
  {
    id: "SUP-PL-CW200-005-A-01",
    spoolNo: "PL-CW200-005-A",
    tag: "H-1043",
    type: "Hanger",
    status: "Welded",
  },
  {
    id: "SUP-PL-CW200-005-A-02",
    spoolNo: "PL-CW200-005-A",
    tag: "A-206",
    type: "Anchor",
    status: "Welded",
  },
  {
    id: "SUP-PL-CW200-005-A-03",
    spoolNo: "PL-CW200-005-A",
    tag: "G-302",
    type: "Guide",
    status: "Welded",
  },
  {
    id: "SUP-PL-CW200-005-A-04",
    spoolNo: "PL-CW200-005-A",
    tag: "S-102",
    type: "Spring",
    status: "Welded",
  },
  // PL-FU300-007-A — mixed (I5 In Progress)
  {
    id: "SUP-PL-FU300-007-A-01",
    spoolNo: "PL-FU300-007-A",
    tag: "H-1044",
    type: "Hanger",
    status: "Welded",
  },
  {
    id: "SUP-PL-FU300-007-A-02",
    spoolNo: "PL-FU300-007-A",
    tag: "A-207",
    type: "Anchor",
    status: "Erected",
  },
  {
    id: "SUP-PL-FU300-007-A-03",
    spoolNo: "PL-FU300-007-A",
    tag: "G-303",
    type: "Guide",
    status: "Not Started",
  },
]

export const SUPPORTED_SEED: SupportedRecord[] = [
  {
    spoolNo: "PL-TK100-003-A",
    confirmedDate: "2025-05-18",
    confirmedBy: "SUP-02",
    w23FormNo: "W23-2025-0149",
    totalSupports: 4,
    remark: "All supports erected and welded per W-23.",
  },
]

export const FIELD_MC_SEED: FieldMaterialCheckRecord[] = [
  // --- Cleared (happy path) — PL-TK100-003-A --------------------------------
  {
    fieldJointId: "fj-2011",
    spoolNo: "PL-TK100-003-A",
    pieces: [
      {
        id: "FHP-fj-2011-01",
        fieldJointId: "fj-2011",
        tag: "STUB-2011-A",
        type: "Pipe Stub",
        heatNumber: "HT-CS-A335P91-99820",
        millCertRef: "MILL-2025-4101",
        status: "Cleared",
      },
      {
        id: "FHP-fj-2011-02",
        fieldJointId: "fj-2011",
        tag: "FLG-2011-B",
        type: "Flange",
        heatNumber: "HT-CS-A335P91-99821",
        millCertRef: "MILL-2025-4102",
        status: "Cleared",
      },
    ],
    inspector: "QC-ENG-01",
    signedOffDate: "2025-05-16",
    wmcFormNo: "WMC-2025-0140",
    remark: "Heat numbers verified against WPS and piping class.",
    nonConformanceCount: 0,
  },
  // --- Ready to Sign — PL-TK100-004-A ---------------------------------------
  {
    fieldJointId: "fj-2015",
    spoolNo: "PL-TK100-004-A",
    pieces: [
      {
        id: "FHP-fj-2015-01",
        fieldJointId: "fj-2015",
        tag: "STUB-2015-A",
        type: "Pipe Stub",
        heatNumber: "HT-CS-A106B-31204",
        millCertRef: "MILL-2025-4103",
        status: "Cleared",
      },
      {
        id: "FHP-fj-2015-02",
        fieldJointId: "fj-2015",
        tag: "ELB-2015-B",
        type: "Fitting",
        heatNumber: "HT-CS-A106B-31218",
        millCertRef: "MILL-2025-4104",
        status: "Cleared",
      },
    ],
    nonConformanceCount: 0,
  },
  // --- Awaiting MC with NC — PL-CW200-005-B ---------------------------------
  {
    fieldJointId: "fj-2016",
    spoolNo: "PL-CW200-005-B",
    pieces: [
      {
        id: "FHP-fj-2016-01",
        fieldJointId: "fj-2016",
        tag: "STUB-2016-A",
        type: "Pipe Stub",
        heatNumber: "HT-SS-316L-55130",
        millCertRef: "MILL-2025-4105",
        status: "Cleared",
      },
      {
        id: "FHP-fj-2016-02",
        fieldJointId: "fj-2016",
        tag: "SOC-2016-B",
        type: "Fitting",
        heatNumber: "HT-SS-316L-55131",
        status: "Non-conformance",
        ncRemark: "Mill certificate missing for socket fitting — supplier chase sent.",
      },
    ],
    nonConformanceCount: 1,
  },
]

export const RFT_SEED: RFTRecord[] = [
  {
    spoolNo: "PL-TK100-003-A",
    rftDate: "2025-05-18",
    autoGenerated: true,
    predecessors: {
      toSiteDate: "2025-05-16",
      erectedDate: "2025-05-17",
      weldedBoltedDate: "2025-05-18",
      supportedDate: "2025-05-18",
    },
  },
]

// ---------------------------------------------------------------------------
// Field Flange Bolt Progress data model (I8) — Easy Piping §19.2.1
// ---------------------------------------------------------------------------

export type BoltingMethod = "Manual" | "Hydraulic Wrench" | "Pneumatic"

export const BOLTING_METHODS: BoltingMethod[] = [
  "Manual",
  "Hydraulic Wrench",
  "Pneumatic",
]

export const TORQUE_TOOLS = [
  "TT-01",
  "TT-04",
  "TT-09",
  "TT-12",
] as const
export type TorqueTool = (typeof TORQUE_TOOLS)[number]

export type FlangeBoltStatus =
  | "Awaiting Torque"
  | "Torque Assigned"
  | "Bolted"
  | "Verified"

export interface FlangeBoltProgressRecord {
  fieldJointId: string         // FK → FIELD_WELD_DATA.id (only when fieldJointType === "Flange Bolt")
  spoolNo: string              // denormalised — must equal the field-weld's spoolNo

  // §19.2.1 step 1: torque assignment
  targetTorqueNm?: number
  boltingMethod?: BoltingMethod
  assignedBy?: string          // from QC_INSPECTORS
  assignedDate?: string        // ISO date

  // §19.2.1 step 2: execution
  boltedDate?: string          // ISO date
  jointer?: string             // free text (jointer code, e.g. "JTR-04")
  tagNo?: string               // free text (e.g. "TAG-FJ2010")
  reportNo?: string            // free text (e.g. "BR-19-2025-0207")

  // §19.2.1 step 3: verification
  verifiedDate?: string        // ISO date
  verifiedBy?: string          // from QC_INSPECTORS
  torqueTool?: TorqueTool

  // free-text observations (visible in Done mode)
  remark?: string
}

export function deriveFlangeBoltStatus(
  record: FlangeBoltProgressRecord | undefined,
): FlangeBoltStatus {
  if (!record) return "Awaiting Torque"
  if (record.verifiedDate) return "Verified"
  if (record.boltedDate) return "Bolted"
  if (record.targetTorqueNm && record.boltingMethod && record.assignedBy) {
    return "Torque Assigned"
  }
  return "Awaiting Torque"
}

export interface SpoolFlangeBoltRollup {
  totalBolts: number
  assigned: number
  bolted: number
  verified: number
  allVerified: boolean
}

export function computeSpoolFlangeBoltRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "id" | "fieldJointType">[],
  records: Pick<FlangeBoltProgressRecord, "fieldJointId" | "targetTorqueNm" | "boltingMethod" | "assignedBy" | "boltedDate" | "verifiedDate">[],
): SpoolFlangeBoltRollup {
  const flangeJoints = fieldWelds.filter(
    (w) => w.spoolNo === spoolNo && w.fieldJointType === "Flange Bolt",
  )
  const totalBolts = flangeJoints.length
  const jointIds = new Set(flangeJoints.map((j) => j.id))

  let assigned = 0
  let bolted = 0
  let verified = 0

  for (const record of records) {
    if (!jointIds.has(record.fieldJointId)) continue
    if (record.verifiedDate) {
      verified += 1
      bolted += 1
      assigned += 1
      continue
    }
    if (record.boltedDate) {
      bolted += 1
      assigned += 1
      continue
    }
    if (record.targetTorqueNm && record.boltingMethod && record.assignedBy) {
      assigned += 1
    }
  }

  const allVerified = totalBolts > 0 && verified === totalBolts

  return { totalBolts, assigned, bolted, verified, allVerified }
}

export const FLANGE_BOLT_SEED: FlangeBoltProgressRecord[] = [
  // Verified — matches the seeded "Bolted" erectionStatus on this joint
  {
    fieldJointId: "fj-2010",
    spoolNo: "PL-FU300-009-A",
    targetTorqueNm: 320,
    boltingMethod: "Hydraulic Wrench",
    assignedBy: "QC-ENG-01",
    assignedDate: "2025-05-14",
    boltedDate: "2025-05-15",
    jointer: "JTR-02",
    tagNo: "TAG-FJ2010",
    reportNo: "BR-19-2025-0210",
    verifiedDate: "2025-05-15",
    verifiedBy: "QC-ENG-02",
    torqueTool: "TT-09",
    remark: "Torque values recorded per §19.2.1.",
  },
  // Verified — second pre-bolted joint
  {
    fieldJointId: "fj-2011",
    spoolNo: "PL-TK100-003-A",
    targetTorqueNm: 540,
    boltingMethod: "Hydraulic Wrench",
    assignedBy: "QC-ENG-01",
    assignedDate: "2025-05-08",
    boltedDate: "2025-05-09",
    jointer: "JTR-04",
    tagNo: "TAG-FJ2011",
    reportNo: "BR-19-2025-0211",
    verifiedDate: "2025-05-09",
    verifiedBy: "QC-ENG-03",
    torqueTool: "TT-04",
    remark: "Cross-pattern torque-up, 4 passes.",
  },
  // Torque Assigned — but no bolt-up yet
  {
    fieldJointId: "fj-2007",
    spoolNo: "PL-FU300-007-A",
    targetTorqueNm: 480,
    boltingMethod: "Hydraulic Wrench",
    assignedBy: "QC-ENG-01",
    assignedDate: "2025-05-17",
    boltedDate: "2025-05-18",
    jointer: "JTR-05",
    tagNo: "TAG-FJ2007",
    reportNo: "BR-19-2025-0207",
    verifiedDate: "2025-05-18",
    verifiedBy: "QC-ENG-02",
    torqueTool: "TT-12",
    remark: "Verified for Welded/Bolted sign-off gate.",
  },
  {
    fieldJointId: "fj-2019",
    spoolNo: "PL-CW200-005-A",
    targetTorqueNm: 300,
    boltingMethod: "Manual",
    assignedBy: "QC-ENG-02",
    assignedDate: "2025-05-17",
    boltedDate: "2025-05-18",
    jointer: "JTR-03",
    tagNo: "TAG-FJ2019",
    reportNo: "BR-19-2025-0219",
    verifiedDate: "2025-05-18",
    verifiedBy: "QC-ENG-01",
    torqueTool: "TT-01",
    remark: "Verified before W-24 welded/bolted confirmation.",
  },
  {
    fieldJointId: "fj-2020",
    spoolNo: "PL-FU300-007-A",
    targetTorqueNm: 480,
    boltingMethod: "Hydraulic Wrench",
    assignedBy: "QC-ENG-03",
    assignedDate: "2025-05-17",
    boltedDate: "2025-05-18",
    jointer: "JTR-06",
    tagNo: "TAG-FJ2020",
    reportNo: "BR-19-2025-0220",
    verifiedDate: "2025-05-18",
    verifiedBy: "QC-ENG-02",
    torqueTool: "TT-09",
    remark: "Verified before W-24 welded/bolted confirmation.",
  },
  {
    fieldJointId: "fj-2021",
    spoolNo: "PL-TK100-003-A",
    targetTorqueNm: 540,
    boltingMethod: "Hydraulic Wrench",
    assignedBy: "QC-ENG-01",
    assignedDate: "2025-05-08",
    boltedDate: "2025-05-09",
    jointer: "JTR-04",
    tagNo: "TAG-FJ2021",
    reportNo: "BR-19-2025-0221",
    verifiedDate: "2025-05-09",
    verifiedBy: "QC-ENG-03",
    torqueTool: "TT-04",
    remark: "Verified before RFT eligibility.",
  },
  // Awaiting Torque is implicit — no record needed for unseeded flange-bolt joints.
]
