import type { ErectionStatus, FieldWeldJoint } from "@/lib/erection-weld-data"
import { AREA_ZONES } from "@/lib/erection-weld-data"

export type SpoolErectionStage =
  | "Awaiting Release"
  | "To Site"
  | "Field Material Check"
  | "Erected"
  | "Welded/Bolted"
  | "Supported"
  | "Field QC Released"
  | "RFT"

export const ERECTION_STAGE_ORDER: SpoolErectionStage[] = [
  "Awaiting Release",
  "To Site",
  "Field Material Check",
  "Erected",
  "Welded/Bolted",
  "Supported",
  "Field QC Released",
  "RFT",
]

export const ERECTION_STAGE_COLOR: Record<
  SpoolErectionStage,
  { bg: string; text: string; rail: string }
> = {
  "Awaiting Release": {
    bg: "bg-slate-50",
    text: "text-slate-600",
    rail: "bg-slate-300",
  },
  "To Site": {
    bg: "bg-amber-50",
    text: "text-amber-700",
    rail: "bg-amber-500",
  },
  "Field Material Check": {
    bg: "bg-cyan-50",
    text: "text-cyan-700",
    rail: "bg-cyan-500",
  },
  Erected: {
    bg: "bg-sky-50",
    text: "text-sky-700",
    rail: "bg-sky-500",
  },
  "Welded/Bolted": {
    bg: "bg-violet-50",
    text: "text-violet-700",
    rail: "bg-violet-500",
  },
  Supported: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    rail: "bg-emerald-500",
  },
  "Field QC Released": {
    bg: "bg-teal-50",
    text: "text-teal-700",
    rail: "bg-teal-500",
  },
  RFT: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    rail: "bg-emerald-700",
  },
}

export interface ToSiteRecord {
  spoolNo: string
  receivedDate: string
  receivedBy: string
  w24FormNo: string
  remark?: string
}

export const AREA_SUPERVISORS = [
  "SUP-01",
  "SUP-02",
  "SUP-03",
  "SUP-04",
] as const

export type AreaSupervisor = (typeof AREA_SUPERVISORS)[number]

export const PLACEMENT_LOCATIONS = AREA_ZONES
export type PlacementLocation = (typeof PLACEMENT_LOCATIONS)[number]

export interface ErectedRecord {
  spoolNo: string
  erectedDate: string
  erectedBy: AreaSupervisor
  w24FormNo: string
  placementLocation: PlacementLocation
  elevation?: string
  remark?: string
}

export interface WeldedBoltedRecord {
  spoolNo: string
  confirmedDate: string
  confirmedBy: string
  w24FormNo: string
  weldedJointCount: number
  boltedJointCount: number
  remark?: string
}

export type SupportType = "Hanger" | "Anchor" | "Guide" | "Spring"
export type SupportStatus = "Not Started" | "Erected" | "Welded"

export interface SupportItem {
  id: string
  spoolNo: string
  tag: string
  type: SupportType
  status: SupportStatus
}

export interface RFTRecord {
  spoolNo: string
  rftDate: string
  autoGenerated: true
  predecessors: {
    toSiteDate: string
    erectedDate: string
    weldedBoltedDate: string
    supportedDate: string
  }
}

export function isSpoolRFTEligible(
  spoolNo: string,
  toSiteRecord?: ToSiteRecord,
  erectedRecord?: ErectedRecord,
  weldedBoltedRecord?: WeldedBoltedRecord,
  supportedRecord?: SupportedRecord,
  flangeRollup?: SpoolFlangeBoltRollup,
  fieldQcReleased = false,
): boolean {
  return (
    toSiteRecord?.spoolNo === spoolNo &&
    erectedRecord?.spoolNo === spoolNo &&
    weldedBoltedRecord?.spoolNo === spoolNo &&
    supportedRecord?.spoolNo === spoolNo &&
    (!flangeRollup || flangeRollup.totalBolts === 0 || flangeRollup.allVerified) &&
    fieldQcReleased
  )
}

export interface SupportedRecord {
  spoolNo: string
  confirmedDate: string
  confirmedBy: AreaSupervisor
  w23FormNo: string
  totalSupports: number
  remark?: string
}

// ---------------------------------------------------------------------------
// Field Material Check data model (I7)
// ---------------------------------------------------------------------------

export type FieldMaterialCheckStatus = "Pending" | "Cleared" | "Non-conformance"

export interface FieldHeatPiece {
  id: string
  fieldJointId: string
  tag: string
  type: "Pipe Stub" | "Fitting" | "Flange" | "Weld Stub"
  heatNumber: string
  millCertRef?: string
  status: FieldMaterialCheckStatus
  ncRemark?: string
}

export interface FieldMaterialCheckRecord {
  fieldJointId: string
  spoolNo: string
  pieces: FieldHeatPiece[]
  inspector?: string
  signedOffDate?: string
  wmcFormNo?: string
  remark?: string
  nonConformanceCount: number
}

export interface SpoolFieldMCRollup {
  totalJoints: number
  clearedJoints: number
  ncJoints: number
  pendingJoints: number
  allCleared: boolean
}

export function computeSpoolFieldMCRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "id">[],
  mcRecords: Pick<FieldMaterialCheckRecord, "fieldJointId" | "pieces" | "signedOffDate">[],
): SpoolFieldMCRollup {
  const joints = fieldWelds.filter((w) => w.spoolNo === spoolNo)
  const totalJoints = joints.length
  const jointIds = new Set(joints.map((j) => j.id))

  let clearedJoints = 0
  let ncJoints = 0
  let pendingJoints = 0

  for (const record of mcRecords) {
    if (!jointIds.has(record.fieldJointId)) continue
    const ncCount = record.pieces.filter((p) => p.status === "Non-conformance").length
    if (record.signedOffDate) {
      clearedJoints += 1
    } else if (ncCount > 0) {
      ncJoints += 1
    } else {
      pendingJoints += 1
    }
  }

  // Joints with no MC record at all count as pending
  const jointsWithRecord = new Set(
    mcRecords.filter((r) => jointIds.has(r.fieldJointId)).map((r) => r.fieldJointId),
  )
  pendingJoints += totalJoints - jointsWithRecord.size

  const allCleared = totalJoints > 0 && clearedJoints === totalJoints

  return { totalJoints, clearedJoints, ncJoints, pendingJoints, allCleared }
}

export interface SpoolWBRollup {
  weldJointsTotal: number
  weldJointsDone: number
  boltJointsTotal: number
  boltJointsDone: number
  allDone: boolean
}

export function computeSpoolWBRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "erectionStatus" | "fieldJointType">[],
): SpoolWBRollup {
  const joints = fieldWelds.filter((w) => w.spoolNo === spoolNo)

  const weldJoints = joints.filter(
    (w) => w.fieldJointType === "Butt Weld" || w.fieldJointType === "Socket Weld",
  )
  const boltJoints = joints.filter((w) => w.fieldJointType === "Flange Bolt")

  const weldDoneStatuses = new Set<ErectionStatus>(["Welded", "Supported", "RFT"])
  const boltDoneStatuses = new Set<ErectionStatus>(["Bolted", "Supported", "RFT"])

  const weldJointsTotal = weldJoints.length
  const weldJointsDone = weldJoints.filter((w) => weldDoneStatuses.has(w.erectionStatus)).length
  const boltJointsTotal = boltJoints.length
  const boltJointsDone = boltJoints.filter((w) => boltDoneStatuses.has(w.erectionStatus)).length

  const allDone =
    weldJointsTotal === weldJointsDone &&
    boltJointsTotal === boltJointsDone &&
    (weldJointsTotal > 0 || boltJointsTotal > 0)

  return {
    weldJointsTotal,
    weldJointsDone,
    boltJointsTotal,
    boltJointsDone,
    allDone,
  }
}

export interface SpoolSupportRollup {
  total: number
  erected: number
  welded: number
  allWelded: boolean
}

export function computeSpoolSupportRollup(
  spoolNo: string,
  supportItems: Pick<SupportItem, "spoolNo" | "status">[],
): SpoolSupportRollup {
  const items = supportItems.filter((item) => item.spoolNo === spoolNo)
  const total = items.length
  const erected = items.filter(
    (item) => item.status === "Erected" || item.status === "Welded",
  ).length
  const welded = items.filter((item) => item.status === "Welded").length
  const allWelded = total > 0 && welded === total

  return { total, erected, welded, allWelded }
}




const ERECTION_STATUS_RANK: Record<ErectionStatus, number> = {
  "Not Started": 0,
  "To Site": 1,
  Erected: 2,
  Welded: 3,
  Bolted: 3,
  Supported: 4,
  RFT: 5,
}

export function deriveSpoolErectionStage(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "erectionStatus">[],
  toSiteRecord?: ToSiteRecord,
  erectedRecord?: ErectedRecord,
  weldedBoltedRecord?: WeldedBoltedRecord,
  supportedRecord?: SupportedRecord,
  rftRecord?: RFTRecord,
  fieldMCRollup?: SpoolFieldMCRollup,
  fieldQcSignedOff?: boolean,
): SpoolErectionStage {
  if (rftRecord?.spoolNo === spoolNo) return "RFT"
  const statuses = fieldWelds
    .filter((fieldWeld) => fieldWeld.spoolNo === spoolNo)
    .map((fieldWeld) => fieldWeld.erectionStatus)

  if (statuses.length === 0) {
    if (erectedRecord) return "Erected"
    // Field Material Check gate for spools with no field welds but MC records
    if (
      toSiteRecord &&
      fieldMCRollup &&
      fieldMCRollup.totalJoints > 0 &&
      (!fieldMCRollup.allCleared || !erectedRecord)
    ) {
      if (!fieldMCRollup.allCleared) return "Field Material Check"
      if (!erectedRecord) return "Field Material Check"
    }
    return toSiteRecord ? "To Site" : "Awaiting Release"
  }

  if (supportedRecord) {
    if (fieldQcSignedOff) return "Field QC Released"
    return "Supported"
  }

  if (statuses.every((status) => ERECTION_STATUS_RANK[status] >= 3)) {
    // Gating: Welded/Bolted stage requires explicit QC sign-off record
    if (weldedBoltedRecord) {
      return "Welded/Bolted"
    }
    // Without record, cap at Erected if erectedRecord exists, otherwise fall through
    if (erectedRecord) {
      return "Erected"
    }
  }

  if (statuses.every((status) => ERECTION_STATUS_RANK[status] >= 2)) {
    return "Erected"
  }

  if (
    erectedRecord &&
    statuses.every((status) => ERECTION_STATUS_RANK[status] <= 2)
  ) {
    return "Erected"
  }

  // Field Material Check gate (inserted between To Site and Erected)
  if (toSiteRecord && fieldMCRollup && fieldMCRollup.totalJoints > 0) {
    if (!fieldMCRollup.allCleared) {
      return "Field Material Check"
    }
    if (!erectedRecord) {
      return "Field Material Check"
    }
    // allCleared + erectedRecord → fall through to existing logic
  }

  if (toSiteRecord) {
    return "To Site"
  }

  if (statuses.some((status) => ERECTION_STATUS_RANK[status] >= 1)) {
    return "To Site"
  }

  return "Awaiting Release"
}






// ---------------------------------------------------------------------------
// Field Flange Bolt Progress data model (I8) — Easy Piping §19.2.1
// ---------------------------------------------------------------------------

export type BoltingMethod = "Manual" | "Hydraulic Wrench" | "Pneumatic"

export const BOLTING_METHODS: BoltingMethod[] = [
  "Manual",
  "Hydraulic Wrench",
  "Pneumatic",
]

export const TORQUE_TOOLS = [
  "TT-01",
  "TT-04",
  "TT-09",
  "TT-12",
] as const
export type TorqueTool = (typeof TORQUE_TOOLS)[number]

export type FlangeBoltStatus =
  | "Awaiting Torque"
  | "Torque Assigned"
  | "Bolted"
  | "Verified"

export interface FlangeBoltProgressRecord {
  fieldJointId: string         // FK → FIELD_WELD_DATA.id (only when fieldJointType === "Flange Bolt")
  spoolNo: string              // denormalised — must equal the field-weld's spoolNo

  // §19.2.1 step 1: torque assignment
  targetTorqueNm?: number
  boltingMethod?: BoltingMethod
  assignedBy?: string          // from QC_INSPECTORS
  assignedDate?: string        // ISO date

  // §19.2.1 step 2: execution
  boltedDate?: string          // ISO date
  jointer?: string             // free text (jointer code, e.g. "JTR-04")
  tagNo?: string               // free text (e.g. "TAG-FJ2010")
  reportNo?: string            // free text (e.g. "BR-19-2025-0207")

  // §19.2.1 step 3: verification
  verifiedDate?: string        // ISO date
  verifiedBy?: string          // from QC_INSPECTORS
  torqueTool?: TorqueTool

  // free-text observations (visible in Done mode)
  remark?: string
}

export function deriveFlangeBoltStatus(
  record: FlangeBoltProgressRecord | undefined,
): FlangeBoltStatus {
  if (!record) return "Awaiting Torque"
  if (record.verifiedDate) return "Verified"
  if (record.boltedDate) return "Bolted"
  if (record.targetTorqueNm && record.boltingMethod && record.assignedBy) {
    return "Torque Assigned"
  }
  return "Awaiting Torque"
}

export interface SpoolFlangeBoltRollup {
  totalBolts: number
  assigned: number
  bolted: number
  verified: number
  allVerified: boolean
}

export function computeSpoolFlangeBoltRollup(
  spoolNo: string,
  fieldWelds: Pick<FieldWeldJoint, "spoolNo" | "id" | "fieldJointType">[],
  records: Pick<FlangeBoltProgressRecord, "fieldJointId" | "targetTorqueNm" | "boltingMethod" | "assignedBy" | "boltedDate" | "verifiedDate">[],
): SpoolFlangeBoltRollup {
  const flangeJoints = fieldWelds.filter(
    (w) => w.spoolNo === spoolNo && w.fieldJointType === "Flange Bolt",
  )
  const totalBolts = flangeJoints.length
  const jointIds = new Set(flangeJoints.map((j) => j.id))

  let assigned = 0
  let bolted = 0
  let verified = 0

  for (const record of records) {
    if (!jointIds.has(record.fieldJointId)) continue
    if (record.verifiedDate) {
      verified += 1
      bolted += 1
      assigned += 1
      continue
    }
    if (record.boltedDate) {
      bolted += 1
      assigned += 1
      continue
    }
    if (record.targetTorqueNm && record.boltingMethod && record.assignedBy) {
      assigned += 1
    }
  }

  const allVerified = totalBolts > 0 && verified === totalBolts

  return { totalBolts, assigned, bolted, verified, allVerified }
}

// Erection demo seeds are derived from the canonical spine.
// See lib/fixtures/derive/erection.ts.
export {
  TO_SITE_SEED,
  ERECTED_SEED,
  WELDED_BOLTED_SEED,
  SUPPORT_SEED,
  SUPPORTED_SEED,
  FIELD_MC_SEED,
  RFT_SEED,
  FLANGE_BOLT_SEED,
} from "@/lib/fixtures"
