import type { WeldJoint, WeldStatus } from "@/lib/weld-data";

export type ErectionStatus =
  | "To Site"
  | "Erected"
  | "Welded"
  | "Bolted"
  | "Supported"
  | "RFT"
  | "Not Started";

export type FieldJointType = "Butt Weld" | "Socket Weld" | "Flange Bolt";

export interface FieldWeldJoint extends WeldJoint {
  erectionStatus: ErectionStatus;
  fieldJointType: FieldJointType;
  areaZone: string;
  rootPercent: number;
  capPercent: number;
  foremanConfirmed?: boolean;
}

export const ERECTION_STATUS_OPTIONS: ErectionStatus[] = [
  "To Site",
  "Erected",
  "Welded",
  "Bolted",
  "Supported",
  "RFT",
  "Not Started",
];

export const FIELD_JOINT_TYPES: FieldJointType[] = [
  "Butt Weld",
  "Socket Weld",
  "Flange Bolt",
];

export const AREA_ZONES = [
  "Area A - North Pipe Rack",
  "Area B - Compressor Hall",
  "Area C - Tank Farm",
  "Area D - Utility Corridor",
];

export const FIELD_WELDERS = [
  "WLD-F01",
  "WLD-F02",
  "WLD-F03",
  "WLD-F04",
  "WLD-F05",
  "WLD-F06",
  "WLD-F07",
  "WLD-F08",
];

export const FIELD_WELD_DATA: FieldWeldJoint[] = [
  // 3 RFT
  {
    id: "fj-2001",
    jointNo: "FJ-2001",
    spoolNo: "PL-TK100-001-A",
    isoNo: "ISO-1001",
    diaInch: '6"',
    materialType: "CS A106B",
    wpsNo: "GTAW-P1-1G",
    welderCode: "WLD-F01",
    weldDate: "14 May 2025",
    dwirNo: "DWIR-2025-2001",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "RFT",
    fieldJointType: "Butt Weld",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-4421",
    fitUpInspector: "ENG-07",
    fitUpDate: "12 May 2025",
    rtNo: "RT-2025-2001",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Field weld accepted. Final RFT signed off.",
  },
  {
    id: "fj-2002",
    jointNo: "FJ-2002",
    spoolNo: "PL-TK100-001-B",
    isoNo: "ISO-1001",
    diaInch: '6"',
    materialType: "CS A106B",
    wpsNo: "GTAW-P1-1G",
    welderCode: "WLD-F02",
    weldDate: "14 May 2025",
    dwirNo: "DWIR-2025-2002",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "RFT",
    fieldJointType: "Butt Weld",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-4421",
    fitUpInspector: "ENG-07",
    fitUpDate: "12 May 2025",
    rtNo: "RT-2025-2002",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "All inspections passed.",
  },
  {
    id: "fj-2003",
    jointNo: "FJ-2003",
    spoolNo: "PL-CW200-003-A",
    isoNo: "ISO-1002",
    diaInch: '12"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-1G",
    welderCode: "WLD-F03",
    weldDate: "13 May 2025",
    dwirNo: "DWIR-2025-2003",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "RFT",
    fieldJointType: "Socket Weld",
    areaZone: "Area B - Compressor Hall",
    rootPercent: 35,
    capPercent: 65,
    heatNo: "HT-5512",
    fitUpInspector: "ENG-03",
    fitUpDate: "11 May 2025",
    rtNo: "RT-2025-2003",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Radiograph accepted.",
  },
  {
    id: "fj-2004",
    jointNo: "FJ-2004",
    spoolNo: "PL-TK100-002-A",
    isoNo: "ISO-1003",
    diaInch: '8"',
    materialType: "CS A335 P91",
    wpsNo: "GTAW-P91-1G",
    welderCode: "WLD-F04",
    weldDate: "10 May 2025",
    dwirNo: "DWIR-2025-2004",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Supported",
    fieldJointType: "Butt Weld",
    areaZone: "Area C - Tank Farm",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-9981",
    fitUpInspector: "ENG-01",
    fitUpDate: "08 May 2025",
    rtNo: "RT-2025-2004",
    rtResult: "Accepted",
    pwhtRequired: true,
    pwhtDate: "11 May 2025",
    foremanConfirmed: true,
    remarks: "PWHT completed per spec.",
  },
  // 1 Supported + 2 Not Started
  {
    id: "fj-2005",
    jointNo: "FJ-2005",
    spoolNo: "PL-TK100-002-B",
    isoNo: "ISO-1003",
    diaInch: '8"',
    materialType: "CS A335 P91",
    wpsNo: "GTAW-P91-1G",
    welderCode: "WLD-F05",
    weldDate: "11 May 2025",
    dwirNo: "DWIR-2025-2005",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Not Started",
    fieldJointType: "Butt Weld",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-9981",
    fitUpInspector: "ENG-01",
    fitUpDate: "09 May 2025",
    rtNo: "RT-2025-2005",
    rtResult: "Accepted",
    pwhtRequired: true,
    pwhtDate: "12 May 2025",
    foremanConfirmed: true,
    remarks: "Support pads welded and inspected.",
  },
  {
    id: "fj-2006",
    jointNo: "FJ-2006",
    spoolNo: "PL-CW200-003-B",
    isoNo: "ISO-1002",
    diaInch: '12"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-1G",
    welderCode: "WLD-F06",
    weldDate: "15 May 2025",
    dwirNo: "DWIR-2025-2006",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Not Started",
    fieldJointType: "Socket Weld",
    areaZone: "Area B - Compressor Hall",
    rootPercent: 35,
    capPercent: 65,
    heatNo: "HT-5512",
    fitUpInspector: "ENG-03",
    fitUpDate: "13 May 2025",
    rtNo: "RT-2025-2006",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Shoe support installed.",
  },
  {
    id: "fj-2007",
    jointNo: "FJ-2007",
    spoolNo: "PL-FU300-007-A",
    isoNo: "ISO-1005",
    diaInch: '4"',
    materialType: "CS A106B",
    wpsNo: "SMAW-P1-2G",
    welderCode: "WLD-F07",
    weldDate: "12 May 2025",
    dwirNo: "DWIR-2025-2007",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Not Started",
    fieldJointType: "Flange Bolt",
    areaZone: "Area D - Utility Corridor",
    rootPercent: 0,
    capPercent: 100,
    heatNo: "HT-3301",
    fitUpInspector: "ENG-02",
    fitUpDate: "10 May 2025",
    rtNo: "RT-2025-2007",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Flange bolted and torqued to spec.",
  },
  // 1 Welded + 1 Bolted + 2 Not Started
  {
    id: "fj-2008",
    jointNo: "FJ-2008",
    spoolNo: "PL-CW200-005-A",
    isoNo: "ISO-1006",
    diaInch: '3"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-2G",
    welderCode: "WLD-F08",
    weldDate: "13 May 2025",
    dwirNo: "DWIR-2025-2008",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Welded",
    fieldJointType: "Butt Weld",
    areaZone: "Area C - Tank Farm",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-5513",
    fitUpInspector: "ENG-05",
    fitUpDate: "12 May 2025",
    rtNo: "RT-2025-2008",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Field weld complete.",
  },
  {
    id: "fj-2009",
    jointNo: "FJ-2009",
    spoolNo: "PL-FU300-007-B",
    isoNo: "ISO-1005",
    diaInch: '4"',
    materialType: "CS A106B",
    wpsNo: "SMAW-P1-2G",
    welderCode: "WLD-F01",
    weldDate: "14 May 2025",
    dwirNo: "DWIR-2025-2009",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Not Started",
    fieldJointType: "Butt Weld",
    areaZone: "Area D - Utility Corridor",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-3301",
    fitUpInspector: "ENG-02",
    fitUpDate: "12 May 2025",
    rtNo: "RT-2025-2009",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "All passes complete.",
  },
  {
    id: "fj-2010",
    jointNo: "FJ-2010",
    spoolNo: "PL-FU300-009-A",
    isoNo: "ISO-FU300-P-009 R0",
    diaInch: '2"',
    materialType: "CS A106B",
    wpsNo: "SMAW-P1-5G",
    welderCode: "WLD-F02",
    weldDate: "15 May 2025",
    dwirNo: "DWIR-2025-2010",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Bolted",
    fieldJointType: "Flange Bolt",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 0,
    capPercent: 100,
    heatNo: "HT-3302",
    fitUpInspector: "ENG-06",
    fitUpDate: "13 May 2025",
    rtNo: "RT-2025-2010",
    rtResult: "Accepted",
    pwhtRequired: false,
    foremanConfirmed: true,
    remarks: "Torque values recorded.",
  },
  {
    id: "fj-2011",
    jointNo: "FJ-2011",
    spoolNo: "PL-TK100-003-A",
    isoNo: "ISO-TK100-P-003 R1",
    diaInch: '10"',
    materialType: "CS A335 P91",
    wpsNo: "GTAW-P91-1G",
    welderCode: "WLD-F03",
    weldDate: "09 May 2025",
    dwirNo: "DWIR-2025-2011",
    status: "Completed" as WeldStatus,
    isLocked: true,
    erectionStatus: "Not Started",
    fieldJointType: "Flange Bolt",
    areaZone: "Area B - Compressor Hall",
    rootPercent: 0,
    capPercent: 100,
    heatNo: "HT-9982",
    fitUpInspector: "ENG-01",
    fitUpDate: "07 May 2025",
    rtNo: "RT-2025-2011",
    rtResult: "Accepted",
    pwhtRequired: true,
    pwhtDate: "10 May 2025",
    foremanConfirmed: true,
    remarks: "Gasket and bolts inspected.",
  },
  // 2 Erected + 1 Not Started
  {
    id: "fj-2012",
    jointNo: "FJ-2012",
    spoolNo: "PL-CW200-006-A",
    isoNo: "ISO-1007",
    diaInch: '6"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-1G",
    welderCode: "WLD-F04",
    weldDate: "14 May 2025",
    dwirNo: "DWIR-2025-2012",
    status: "In Progress" as WeldStatus,
    isLocked: false,
    erectionStatus: "Erected",
    fieldJointType: "Butt Weld",
    areaZone: "Area C - Tank Farm",
    rootPercent: 40,
    capPercent: 0,
    heatNo: "HT-5514",
    fitUpInspector: "ENG-03",
    fitUpDate: "13 May 2025",
    remarks: "Spool erected. Root pass pending.",
  },
  {
    id: "fj-2013",
    jointNo: "FJ-2013",
    spoolNo: "PL-CW200-008-A",
    isoNo: "ISO-CW200-P-008 R0",
    diaInch: '3"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-5G",
    welderCode: "WLD-F05",
    weldDate: "15 May 2025",
    dwirNo: "DWIR-2025-2013",
    status: "In Progress" as WeldStatus,
    isLocked: false,
    erectionStatus: "Erected",
    fieldJointType: "Socket Weld",
    areaZone: "Area D - Utility Corridor",
    rootPercent: 35,
    capPercent: 0,
    heatNo: "HT-5515",
    fitUpInspector: "ENG-05",
    fitUpDate: "14 May 2025",
    remarks: "Aligned and tacked. Welding in progress.",
  },
  {
    id: "fj-2014",
    jointNo: "FJ-2014",
    spoolNo: "PL-FU300-011-A",
    isoNo: "ISO-FU300-P-011 R1",
    diaInch: '8"',
    materialType: "CS A335 P91",
    wpsNo: "GTAW-P91-5G",
    welderCode: "WLD-F06",
    weldDate: "13 May 2025",
    dwirNo: "DWIR-2025-2014",
    status: "In Progress" as WeldStatus,
    isLocked: false,
    erectionStatus: "Not Started",
    fieldJointType: "Butt Weld",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 40,
    capPercent: 0,
    heatNo: "HT-9985",
    fitUpInspector: "ENG-04",
    fitUpDate: "11 May 2025",
    remarks: "Pre-heating applied. Root pass started.",
  },
  // 2 To Site
  {
    id: "fj-2015",
    jointNo: "FJ-2015",
    spoolNo: "PL-TK100-004-A",
    isoNo: "ISO-TK100-P-004 R2",
    diaInch: '16"',
    materialType: "CS A106B",
    wpsNo: "SAW-P1-1G",
    welderCode: "WLD-F07",
    weldDate: "",
    dwirNo: "DWIR-2025-2015",
    status: "Not Started" as WeldStatus,
    isLocked: false,
    erectionStatus: "To Site",
    fieldJointType: "Butt Weld",
    areaZone: "Area B - Compressor Hall",
    rootPercent: 0,
    capPercent: 0,
    remarks: "Awaiting delivery to site.",
  },
  {
    id: "fj-2016",
    jointNo: "FJ-2016",
    spoolNo: "PL-CW200-005-B",
    isoNo: "ISO-1006",
    diaInch: '3"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-2G",
    welderCode: "WLD-F08",
    weldDate: "",
    dwirNo: "DWIR-2025-2016",
    status: "Not Started" as WeldStatus,
    isLocked: false,
    erectionStatus: "To Site",
    fieldJointType: "Socket Weld",
    areaZone: "Area C - Tank Farm",
    rootPercent: 0,
    capPercent: 0,
    remarks: "Transport scheduled.",
  },
  // 8 Not Started total (one is Rejected for weld status)
  {
    id: "fj-2017",
    jointNo: "FJ-2017",
    spoolNo: "PL-FU300-009-B",
    isoNo: "ISO-FU300-P-009 R0",
    diaInch: '2"',
    materialType: "CS A106B",
    wpsNo: "SMAW-P1-5G",
    welderCode: "WLD-F01",
    weldDate: "11 May 2025",
    dwirNo: "DWIR-2025-2017",
    status: "Rejected" as WeldStatus,
    isLocked: false,
    erectionStatus: "Not Started",
    fieldJointType: "Butt Weld",
    areaZone: "Area D - Utility Corridor",
    rootPercent: 40,
    capPercent: 60,
    heatNo: "HT-3303",
    fitUpInspector: "ENG-06",
    fitUpDate: "09 May 2025",
    rtNo: "RT-2025-2017",
    rtResult: "Rejected",
    pwhtRequired: false,
    foremanConfirmed: false,
    remarks: "Porosity at root. Requires re-weld.",
  },
  {
    id: "fj-2018",
    jointNo: "FJ-2018",
    spoolNo: "PL-TK100-005-A",
    isoNo: "ISO-TK100-P-005 R1",
    diaInch: '4"',
    materialType: "SS 316L",
    wpsNo: "GTAW-P8-1G",
    welderCode: "WLD-F02",
    weldDate: "",
    dwirNo: "DWIR-2025-2018",
    status: "Not Started" as WeldStatus,
    isLocked: false,
    erectionStatus: "Not Started",
    fieldJointType: "Socket Weld",
    areaZone: "Area A - North Pipe Rack",
    rootPercent: 0,
    capPercent: 0,
    remarks: "Not yet released for erection.",
  },
];
