"use client"

import Link from "next/link"
import { useSearchParams } from "next/navigation"
import { useEffect, useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { getSupabaseBrowserClient } from "@/lib/supabase/browser-client"
import { useSupabaseAuth } from "@/contexts/supabase-auth-context"
import { useOptionalAccess } from "@/modules/access/ui/access-context"
import { assignManagedItemClearance, assignManagedLineCheck } from "../application/manage-line-check"
import { assignBlinding, assignReinstatement, listFlangeJointReadiness, listProjectTeams, listPunchItems, listTestPackCatalog, listTestPackMembers, type FlangeJointReadinessRow, type ProjectTeamRow, type TestPackCatalogRow, type TestPackMemberRow } from "../infrastructure/supabase-pressure-test-repository"
import { getPressureTestRequestConfig, type PressureTestRequestType } from "./pressure-test-ui-model"

interface Props { requestType: PressureTestRequestType; title?: string; description?: string; progressHref?: string }

export function RequestPreparationScreen({ requestType, title, description, progressHref }: Props) {
  const auth = useSupabaseAuth(); const access = useOptionalAccess(); const projectId = auth.access?.projectId; const params = useSearchParams(); const queryPackId = params.get("testPackId")
  const config = getPressureTestRequestConfig(requestType)
  const [packs, setPacks] = useState<TestPackCatalogRow[]>([]); const [selectedPack, setSelectedPack] = useState(queryPackId ?? ""); const [members, setMembers] = useState<TestPackMemberRow[]>([]); const [punches, setPunches] = useState<Record<string, unknown>[]>([]); const [flanges, setFlanges] = useState<FlangeJointReadinessRow[]>([]); const [teams, setTeams] = useState<ProjectTeamRow[]>([]); const [selectedTargets, setSelectedTargets] = useState<string[]>([]); const [teamId, setTeamId] = useState(""); const [assignedOn, setAssignedOn] = useState(new Date().toISOString().slice(0, 10)); const [requestId, setRequestId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  const canManage = access?.can("testpack.manage") ?? false

  useEffect(() => { if (!projectId) return; let active = true; const client = getSupabaseBrowserClient(); const load = async () => { const nextPacks = await listTestPackCatalog(client, projectId); const nextTeams = await listProjectTeams(client, projectId, config.teamType); if (!active) return; setPacks(nextPacks); setTeams(nextTeams); setTeamId((current) => current || nextTeams[0]?.id || ""); setSelectedPack((current) => current || queryPackId || nextPacks[0]?.id || "") }; void load().catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Could not load preparation data") }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [projectId, requestType, queryPackId])
  useEffect(() => { if (!projectId || !selectedPack) return; let active = true; const client = getSupabaseBrowserClient(); const load = async () => { const [nextMembers, nextFlanges] = await Promise.all([listTestPackMembers(client, projectId, selectedPack), listFlangeJointReadiness(client, projectId)]); const memberIds = new Set(nextMembers.map((member) => member.isometric_id)); const nextPunches = requestType === "item_clearance" ? await listPunchItems(client, projectId, selectedPack) : []; if (!active) return; setMembers(nextMembers); setPunches(nextPunches); setFlanges(nextFlanges.filter((flange) => memberIds.has(flange.isometric_id))); setSelectedTargets([]) }; void load().catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Could not load scoped worklist") }); return () => { active = false } }, [projectId, selectedPack, requestType])

  const targets = useMemo(() => requestType === "line_check" ? members.map((member) => ({ id: member.isometric_id ?? "", label: member.iso_number ?? member.isometric_id ?? "" })) : requestType === "item_clearance" ? punches.map((punch) => ({ id: String(punch.id ?? ""), label: `${String(punch.item_number ?? punch.id)} · ISO ${String(punch.isometric_id ?? "")}` })) : requestType === "reinstatement" ? flanges.map((flange) => ({ id: flange.flange_joint_revision_id ?? "", label: `${flange.category_code ?? "?"} · ${flange.flange_number ?? flange.flange_joint_revision_id}` })) : selectedPack ? [{ id: selectedPack, label: packs.find((pack) => pack.id === selectedPack)?.testPackNumber ?? selectedPack }] : [], [flanges, members, packs, punches, requestType, selectedPack])
  const toggle = (id: string, checked: boolean) => setSelectedTargets((current) => checked ? [...current, id] : current.filter((item) => item !== id))
  const assign = async () => { if (!projectId || !selectedPack || !teamId || !canManage) return; setError(null); try { let result: unknown; if (requestType === "line_check") result = await assignManagedLineCheck(getSupabaseBrowserClient(), { testPackId: selectedPack, isometricIds: selectedTargets, teamId, assignedDate: assignedOn }); else if (requestType === "item_clearance") result = await assignManagedItemClearance(getSupabaseBrowserClient(), { testPackId: selectedPack, punchItemIds: selectedTargets, teamId, assignedDate: assignedOn }); else if (requestType === "blinding") result = await assignBlinding(getSupabaseBrowserClient(), selectedPack, teamId, assignedOn, `browser-blinding-${Date.now()}`); else result = await assignReinstatement(getSupabaseBrowserClient(), selectedPack, selectedTargets, teamId, assignedOn, `browser-reinstatement-${Date.now()}`); const value = result as { ok?: boolean; value?: { id?: string }; errors?: Record<string, string> }; if (value.ok === false) { setError(Object.values(value.errors ?? {}).join("; ")); return }; const id = value.value?.id ?? (value as { id?: string }).id; setRequestId(id ?? null) } catch (cause) { setError(cause instanceof Error ? cause.message : "Assignment failed") } }
  if (!projectId) return <p className="text-sm text-muted-foreground">Select a project to prepare a request.</p>
  if (loading) return <Skeleton className="h-64 w-full" />
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">{title ?? config.title} · Preparation</h1><p className="text-sm text-muted-foreground">{description ?? config.description}</p></div>{error && <p className="text-sm text-destructive">{error}</p>}<Card><CardHeader><CardTitle>Server-scoped assignment</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-3"><label className="text-xs text-muted-foreground">Test Pack<select className="h-9 w-full rounded border bg-transparent px-3 text-sm" value={selectedPack} onChange={(event) => setSelectedPack(event.target.value)} disabled={loading}><option value="">Select a Test Pack</option>{packs.map((pack) => <option key={pack.id} value={pack.id}>{pack.testPackNumber} · rev {pack.revisionNo}</option>)}</select></label><label className="text-xs text-muted-foreground">Team<select className="h-9 w-full rounded border bg-transparent px-3 text-sm" value={teamId} onChange={(event) => setTeamId(event.target.value)} disabled={!canManage}><option value="">Select a {config.teamType} team</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.code} · {team.description}</option>)}</select></label><label className="text-xs text-muted-foreground">Assigned date<Input type="date" value={assignedOn} onChange={(event) => setAssignedOn(event.target.value)} disabled={!canManage} /></label></CardContent></Card><Card><CardHeader><CardTitle>{config.targetLabel} targets</CardTitle></CardHeader><CardContent className="space-y-2">{targets.map((target) => <label key={target.id} className="flex items-center gap-2 rounded border p-2 text-sm"><input type="checkbox" checked={selectedTargets.includes(target.id)} onChange={(event) => toggle(target.id, event.target.checked)} disabled={!canManage || requestType === "blinding"} /><span>{target.label}</span></label>)}{targets.length === 0 && <p className="text-sm text-muted-foreground">No eligible server-projected targets for this Test Pack.</p>}<div className="flex flex-wrap gap-3"><Button type="button" onClick={() => void assign()} disabled={!canManage || !teamId || (requestType !== "blinding" && selectedTargets.length === 0)}>Assign request</Button>{progressHref && <Link className="rounded border px-4 py-2 text-sm" href={`${progressHref}${selectedPack ? `?testPackId=${selectedPack}` : ""}`}>Open progress</Link>}{requestId && <Link className="rounded border px-4 py-2 text-sm" href={config.printPath.replace("{requestId}", requestId)}>Open printable request {requestId.slice(0, 8)}</Link>}</div><p className="text-xs text-muted-foreground">Eligibility and duplicate assignment are checked by the RPC; the browser never marks a target ready locally.</p></CardContent></Card></div>
}
