import type { SupabaseClient } from "@supabase/supabase-js"
import type { Database } from "@/lib/supabase/database.types"
import type { ImportIssue } from "@/modules/imports/domain/import-issue"
import type { ImportJob, ImportJobStatus } from "@/modules/imports/domain/import-job"
import type { StagingRow } from "../domain/definition"
import type { ChangeType, PreviewChangeItem } from "../domain/diff"
import type { EngineeringEntityType } from "../domain/entity"
import type { RevisionDecision, RevisionStatus } from "../domain/revision"
import type { SpoolgenFileRole } from "../domain/spoolgen-file"
import { mapSupabaseEngineeringError } from "./supabase-engineering-errors"

export const SPOOLING_BUCKET = "project-spooling"
export const spoolingObjectPath = (projectId: string, jobId: string, role: SpoolgenFileRole) => `${projectId}/${jobId}/${role}.txt`
type Row = Record<string, any>
const toImportJob = (row: Row): ImportJob => ({ id: row.id, projectId: row.project_id, importType: row.import_type, status: row.status as ImportJobStatus, sourceFileName: row.source_file_name ?? null, sourceMediaType: row.source_media_type ?? null, sourceSizeBytes: row.source_size_bytes ?? null, sourceChecksum: row.source_checksum ?? null, storagePath: row.storage_path ?? null, conflictsConfirmed: row.conflicts_confirmed === true, appliedRowCount: row.applied_row_count ?? 0, affectedEntityIds: row.affected_entity_ids ?? [], failureReason: row.failure_reason ?? null, createdAt: row.created_at, validatedAt: row.validated_at ?? null, appliedAt: row.applied_at ?? null, canceledAt: row.canceled_at ?? null })
export function toPreviewChangeItem(row: Row): PreviewChangeItem { const entityType = row.entity_type as EngineeringEntityType; return { isoNumber: row.iso_number, entityType, entityKey: row.entity_key, spoolNumber: entityType === "spool" ? row.entity_key : row.next_payload?.spool_number ?? row.previous_payload?.spool_number ?? null, changeType: row.change_type as ChangeType, requiresDecision: row.requires_decision === true, decision: row.decision as RevisionDecision | null } }
const fail = (error: { code?: string; message?: string } | null) => { if (error) throw new Error(mapSupabaseEngineeringError(error)) }
const required = <T>(data: T | null): T => { if (data === null) throw new Error(mapSupabaseEngineeringError(null)); return data }

export async function createSpoolingImportJob(client: SupabaseClient<Database>, projectId: string, comment: string | null): Promise<ImportJob> { const { data, error } = await client.rpc("create_spooling_import_job", { target_project_id: projectId, job_comment: comment ?? undefined }); fail(error); return toImportJob(required(data)) }
export async function uploadSpoolgenFile(client: SupabaseClient<Database>, objectPath: string, file: File): Promise<void> { const { error } = await client.storage.from(SPOOLING_BUCKET).upload(objectPath, file, { upsert: true, contentType: "text/plain" }); fail(error) }
export async function registerSpoolgenFile(client: SupabaseClient<Database>, jobId: string, role: SpoolgenFileRole, file: File, checksum: string, objectPath: string): Promise<void> { const { error } = await client.rpc("register_spooling_import_file", { target_job_id: jobId, role, file_name: file.name, media_type: file.type || "text/plain", size_bytes: file.size, checksum, object_path: objectPath }); fail(error) }
export async function recordSpoolingValidation(client: SupabaseClient<Database>, jobId: string, rows: readonly StagingRow[], issues: readonly ImportIssue[]): Promise<ImportJob> { const { data, error } = await client.rpc("record_spooling_validation", { target_job_id: jobId, parsed_rows: rows.map((row) => ({ row_number: row.rowNumber, raw_values: row.rawValues, normalized_values: row.normalizedValues, action: row.action })), parsed_issues: issues.map((issue) => ({ row_number: issue.rowNumber, column_name: issue.columnName, severity: issue.severity, code: issue.code, message: issue.message })) }); fail(error); return toImportJob(required(data)) }
export interface ValidationCounts { blockerCount: number; warningCount: number; unresolvedCount: number }
export async function revalidateSpoolingImportJob(client: SupabaseClient<Database>, jobId: string): Promise<ValidationCounts> { const { data, error } = await client.rpc("revalidate_spooling_import_job", { target_job_id: jobId }); fail(error); const row = required(data)[0]; return { blockerCount: row?.blocker_count ?? 0, warningCount: row?.warning_count ?? 0, unresolvedCount: row?.unresolved_count ?? 0 } }
export async function loadPreview(client: SupabaseClient<Database>, jobId: string): Promise<PreviewChangeItem[]> { const { data, error } = await client.rpc("preview_spooling_import", { target_job_id: jobId }); fail(error); return (data ?? []).map(toPreviewChangeItem) }
export async function recordRevisionDecision(client: SupabaseClient<Database>, jobId: string, item: PreviewChangeItem, decision: RevisionDecision, comment: string | null): Promise<void> { const { error } = await client.rpc("record_revision_decision", { target_job_id: jobId, target_iso_number: item.isoNumber, target_entity_type: item.entityType, target_entity_key: item.entityKey, chosen_decision: decision, decision_comment: comment ?? undefined }); fail(error) }
export async function applySpoolingImportJob(client: SupabaseClient<Database>, jobId: string): Promise<ImportJob> { const { data, error } = await client.rpc("apply_spooling_import_job", { target_job_id: jobId }); fail(error); return toImportJob(required(data)) }
export async function createManualRevision(client: SupabaseClient<Database>, isometricId: string, revisionNumber: string, comment: string | null, decisions: readonly { entity_type: EngineeringEntityType; entity_key: string; decision: RevisionDecision }[]): Promise<void> { const { error } = await client.rpc("create_manual_revision", { target_isometric_id: isometricId, new_revision_number: revisionNumber, revision_comment: comment ?? undefined, decisions: [...decisions] }); fail(error) }
export async function loadSpoolingJobs(client: SupabaseClient<Database>, projectId: string): Promise<ImportJob[]> { const { data, error } = await client.from("import_jobs").select("id, project_id, import_type, status, source_file_name, source_media_type, source_size_bytes, source_checksum, storage_path, conflicts_confirmed, applied_row_count, affected_entity_ids, failure_reason, created_at, validated_at, applied_at, canceled_at").eq("project_id", projectId).eq("import_type", "spooling_definition").order("created_at", { ascending: false }); fail(error); return (data ?? []).map(toImportJob) }
export async function loadJobIssues(client: SupabaseClient<Database>, jobId: string): Promise<ImportIssue[]> { const { data, error } = await client.from("import_job_issues").select("row_number, column_name, severity, code, message").eq("job_id", jobId).order("row_number", { ascending: true }); fail(error); return (data ?? []).map((row) => ({ rowNumber: row.row_number, columnName: row.column_name, severity: row.severity, code: row.code, message: row.message })) }
export interface IsometricSummary { id: string; isoNumber: string; acceptedRevisionId: string | null; acceptedRevisionNumber: string | null }
export async function loadIsometrics(client: SupabaseClient<Database>, projectId: string): Promise<IsometricSummary[]> { const { data, error } = await client.from("isometrics").select("id, iso_number, isometric_revisions(id, revision_number, status)").eq("project_id", projectId).order("iso_number"); fail(error); return (data ?? []).map((row: any) => { const accepted = row.isometric_revisions?.find((revision: any) => revision.status === "accepted"); return { id: row.id, isoNumber: row.iso_number, acceptedRevisionId: accepted?.id ?? null, acceptedRevisionNumber: accepted?.revision_number ?? null } }) }
export interface RevisionSummary { id: string; revisionNumber: string; status: RevisionStatus; createdAt: string; acceptedAt: string | null; supersededAt: string | null; comment: string | null }
export async function loadRevisionHistory(client: SupabaseClient<Database>, isometricId: string): Promise<RevisionSummary[]> { const { data, error } = await client.from("isometric_revisions").select("id, revision_number, status, created_at, accepted_at, superseded_at, comment").eq("isometric_id", isometricId).order("revision_ordinal", { ascending: false }); fail(error); return (data ?? []).map((row) => ({ id: row.id, revisionNumber: row.revision_number, status: row.status as RevisionStatus, createdAt: row.created_at, acceptedAt: row.accepted_at, supersededAt: row.superseded_at, comment: row.comment })) }
export interface SpoolNode { id: string; spoolNumber: string; isRemoved: boolean; weldNumbers: string[]; supportNumbers: string[]; flangeNumbers: string[]; identCodes: string[] }
export async function loadRevisionGraph(client: SupabaseClient<Database>, revisionId: string): Promise<SpoolNode[]> { const { data, error } = await client.from("spool_revisions").select("id, is_removed, spools(spool_number), weld_joint_revisions(weld_joints(weld_number)), support_revisions(supports(support_number)), flange_joint_revisions(flange_joints(flange_number)), spool_revision_materials(ident_code)").eq("isometric_revision_id", revisionId); fail(error); return (data ?? []).map((row: any) => ({ id: row.id, spoolNumber: row.spools?.spool_number ?? "", isRemoved: row.is_removed === true, weldNumbers: (row.weld_joint_revisions ?? []).map((entry: any) => entry.weld_joints?.weld_number).filter(Boolean).sort(), supportNumbers: (row.support_revisions ?? []).map((entry: any) => entry.supports?.support_number).filter(Boolean).sort(), flangeNumbers: (row.flange_joint_revisions ?? []).map((entry: any) => entry.flange_joints?.flange_number).filter(Boolean).sort(), identCodes: (row.spool_revision_materials ?? []).map((entry: any) => entry.ident_code).filter(Boolean).sort() })).sort((a, b) => a.spoolNumber.localeCompare(b.spoolNumber)) }
